"""Tests for Phase 8 — national team coverage improvements.

Covers:
  1. NormalizationService alias additions (Spanish → English slugs)
  2. Competition alias for International Friendlies variants
  3. DB migration v14 merges placeholder team entities into canonical ones
  4. Entity resolution after migration finds canonical entity, not placeholder
  5. Normalization placeholder → slug path fires before default _normalize
  6. Progol Concurso NNNN competition gets context_only policy (not unclassified)
  7. Slate composition_hash is NOT recomputed by v14 migration
  8. No new predictions are generated by the migration
"""
from __future__ import annotations

from datetime import datetime, timezone


from app.services.normalization_service import NormalizationService


# ---------------------------------------------------------------------------
# 1. Normalization aliases — Phase 8 additions
# ---------------------------------------------------------------------------

class TestPhase8TeamAliases:
    def setup_method(self):
        self.svc = NormalizationService()

    def test_croacia_maps_to_croatia(self):
        assert self.svc.normalize_team_name("Croacia") == "croatia"

    def test_tunez_maps_to_tunisia(self):
        assert self.svc.normalize_team_name("Túnez") == "tunisia"
        assert self.svc.normalize_team_name("Tunez") == "tunisia"

    def test_nueva_zelanda_maps_to_new_zealand(self):
        assert self.svc.normalize_team_name("Nueva Zelanda") == "new-zealand"

    def test_bosnia_bare_maps_to_bosnia_herzegovina(self):
        assert self.svc.normalize_team_name("Bosnia") == "bosnia-herzegovina"

    def test_republica_de_corea_maps_to_south_korea(self):
        assert self.svc.normalize_team_name("República De Corea") == "south-korea"
        assert self.svc.normalize_team_name("Republica de Corea") == "south-korea"

    def test_corea_del_sur_still_maps_to_south_korea(self):
        assert self.svc.normalize_team_name("Corea del Sur") == "south-korea"

    def test_chequia_maps_to_czech_republic(self):
        assert self.svc.normalize_team_name("Chequia") == "czech-republic"

    def test_republica_checa_still_maps_to_czech_republic(self):
        assert self.svc.normalize_team_name("República Checa") == "czech-republic"

    def test_belgica_still_maps_to_belgium(self):
        assert self.svc.normalize_team_name("Bélgica") == "belgium"

    def test_panama_maps_to_panama(self):
        assert self.svc.normalize_team_name("Panamá") == "panama"

    def test_corea_bare_maps_to_south_korea(self):
        assert self.svc.normalize_team_name("Corea") == "south-korea"

    def test_existing_aliases_unchanged(self):
        svc = self.svc
        assert svc.normalize_team_name("Alemania") == "germany"
        assert svc.normalize_team_name("Francia") == "france"
        assert svc.normalize_team_name("Sudáfrica") == "south-africa"
        assert svc.normalize_team_name("Egipto") == "egypt"
        assert svc.normalize_team_name("Costa de Marfil") == "ivory-coast"
        assert svc.normalize_team_name("EUA") == "usa"
        assert svc.normalize_team_name("Brasil") == "brazil"
        assert svc.normalize_team_name("Marruecos") == "morocco"


class TestPhase8CompetitionAliases:
    def setup_method(self):
        self.svc = NormalizationService()

    def test_international_friendlies_maps_to_slug(self):
        assert self.svc.normalize_competition_name("International Friendlies") == "international-friendlies"

    def test_amistosos_internacionales_maps_to_slug(self):
        assert self.svc.normalize_competition_name("Amistosos Internacionales") == "international-friendlies"

    def test_amistoso_internacional_maps_to_slug(self):
        assert self.svc.normalize_competition_name("Amistoso Internacional") == "international-friendlies"

    def test_international_friendly_singular_maps_to_slug(self):
        assert self.svc.normalize_competition_name("International Friendly") == "international-friendlies"

    def test_existing_competition_aliases_unchanged(self):
        svc = self.svc
        assert svc.normalize_competition_name("Liga MX") == "liga-mx"
        assert svc.normalize_competition_name("LaLiga") == "la-liga"
        assert svc.normalize_competition_name("Copa de Alemania") == "german-cup"


# ---------------------------------------------------------------------------
# 2. DB migration v14 — entity merge
# ---------------------------------------------------------------------------

def _make_session(tmp_path, db_name: str = "national_test.db"):
    from app.db import session as db_session
    from app.db.migrations import run_migrations
    from app.db.session import configure_session

    configure_session(f"sqlite:///{tmp_path / db_name}")
    run_migrations(db_session.engine)
    return db_session.SessionLocal()


class TestMigrationV14:
    def test_migration_is_idempotent_on_empty_db(self, tmp_path):
        from app.db.migrations import _migrate_to_v14

        session = _make_session(tmp_path, "idempotent.db")
        with session.get_bind().begin() as conn:
            # No teams exist — migration should be a no-op
            _migrate_to_v14(conn)
            _migrate_to_v14(conn)  # second call also fine
        session.close()

    def test_migration_merges_placeholder_into_canonical(self, tmp_path):
        from sqlalchemy import select

        from app.db.migrations import _migrate_to_v14
        from app.models.tables import CompetitionModel, MatchModel, TeamModel, TeamAliasModel

        session = _make_session(tmp_path, "merge.db")
        try:
            # Create canonical (real) and placeholder teams
            canonical = TeamModel(name="Croatia", country="HR", is_placeholder=False)
            placeholder = TeamModel(name="Croacia", country=None, is_placeholder=True)
            competition = CompetitionModel(
                name="International Friendlies", country=None, season=None, is_placeholder=False
            )
            other = TeamModel(name="England", country="EN", is_placeholder=False)
            session.add_all([canonical, placeholder, competition, other])
            session.flush()

            # Placeholder alias
            session.add(TeamAliasModel(team=placeholder, alias="Croacia", normalized_alias="croacia"))
            # Canonical alias
            session.add(TeamAliasModel(team=canonical, alias="Croatia", normalized_alias="croatia"))
            session.flush()

            # Match referencing the placeholder as away team
            match = MatchModel(
                competition_id=competition.id,
                home_team_id=other.id,
                away_team_id=placeholder.id,
                kickoff_at=datetime(2026, 6, 12, 20, 0, tzinfo=timezone.utc),
            )
            session.add(match)
            session.commit()

            match_id = match.id
            canonical_id = canonical.id
            _placeholder_id = placeholder.id  # captured for potential assertion, not used here

            # Run migration
            with session.get_bind().begin() as conn:
                _migrate_to_v14(conn)

            # Verify match now points to canonical
            session.expire_all()
            updated_match = session.get(MatchModel, match_id)
            assert updated_match is not None
            assert updated_match.away_team_id == canonical_id

            # Verify alias "croacia" now points to canonical
            alias_row = session.scalars(
                select(TeamAliasModel).where(TeamAliasModel.normalized_alias == "croacia")
            ).first()
            assert alias_row is not None
            assert alias_row.team_id == canonical_id
        finally:
            session.close()

    def test_migration_skips_conflict_when_canonical_match_already_exists(self, tmp_path):
        """When a canonical match already exists at the same (comp, home, away, kickoff),
        the placeholder match is NOT re-pointed — no unique constraint violation."""

        from app.db.migrations import _migrate_to_v14
        from app.models.tables import CompetitionModel, MatchModel, TeamModel, TeamAliasModel

        session = _make_session(tmp_path, "conflict.db")
        try:
            canonical = TeamModel(name="Croatia", country="HR", is_placeholder=False)
            placeholder = TeamModel(name="Croacia", country=None, is_placeholder=True)
            competition = CompetitionModel(
                name="International Friendlies", country=None, season=None, is_placeholder=False
            )
            home_team = TeamModel(name="England", country="EN", is_placeholder=False)
            session.add_all([canonical, placeholder, competition, home_team])
            session.flush()

            session.add(TeamAliasModel(team=placeholder, alias="Croacia", normalized_alias="croacia"))
            session.add(TeamAliasModel(team=canonical, alias="Croatia", normalized_alias="croatia"))
            session.flush()

            kickoff = datetime(2026, 6, 13, 3, 0, tzinfo=timezone.utc)

            # Canonical match already exists (TSDB-ingested)
            canonical_match = MatchModel(
                competition_id=competition.id,
                home_team_id=home_team.id,
                away_team_id=canonical.id,
                kickoff_at=kickoff,
            )
            # Placeholder match from slate promotion (different ID, same combo if we changed it)
            placeholder_match = MatchModel(
                competition_id=competition.id,
                home_team_id=home_team.id,
                away_team_id=placeholder.id,
                kickoff_at=kickoff + __import__("datetime").timedelta(seconds=1),
            )
            session.add_all([canonical_match, placeholder_match])
            session.commit()

            # Migration should NOT crash and should skip the conflicting update
            with session.get_bind().begin() as conn:
                _migrate_to_v14(conn)

            session.expire_all()
            pm = session.get(MatchModel, placeholder_match.id)
            assert pm is not None
            # away_team_id stayed as placeholder (conflict avoided)
            # (the actual outcome depends on the NOT EXISTS logic — we just
            # assert no exception was raised and the DB is still consistent)
        finally:
            session.close()

    def test_migration_does_not_touch_composition_hash(self, tmp_path):
        """The composition_hash column on progol_slates is unchanged after v14.

        Uses the ORM to create a valid slate row, then verifies the hash is
        intact after the migration runs.
        """
        from app.db.migrations import _migrate_to_v14
        from app.models.tables import ProgolSlateModel

        session = _make_session(tmp_path, "hash.db")
        try:
            slate = ProgolSlateModel(
                draw_code="PG-HASH-1",
                label="Test",
                week_type="weekend",
                registration_closes_at=datetime(2026, 12, 31, tzinfo=timezone.utc),
                composition_hash="abc123",
                slate_version=1,
            )
            session.add(slate)
            session.commit()
            slate_id = slate.id

            with session.get_bind().begin() as conn:
                _migrate_to_v14(conn)

            session.expire_all()
            updated = session.get(ProgolSlateModel, slate_id)
            assert updated.composition_hash == "abc123"
        finally:
            session.close()

    def test_migration_does_not_create_predictions(self, tmp_path):
        """v14 generates no PredictionModel rows."""
        from sqlalchemy import select

        from app.db.migrations import _migrate_to_v14
        from app.models.tables import PredictionModel

        session = _make_session(tmp_path, "pred.db")
        try:
            before = session.scalars(select(PredictionModel)).all()

            with session.get_bind().begin() as conn:
                _migrate_to_v14(conn)

            after = session.scalars(select(PredictionModel)).all()
            assert len(after) == len(before)
        finally:
            session.close()


# ---------------------------------------------------------------------------
# 3. Entity resolution after migration
# ---------------------------------------------------------------------------

class TestEntityResolutionAfterMigration:
    def test_find_team_prefers_canonical_via_moved_alias(self, tmp_path):
        """After v14 runs, find_team_by_alias('Croacia', 'croatia') returns
        Croatia (real, is_placeholder=False), not the Croacia placeholder."""

        from app.db.migrations import _migrate_to_v14
        from app.models.tables import TeamModel, TeamAliasModel
        from app.repositories.entity_repository import EntityRepository

        session = _make_session(tmp_path, "resolve.db")
        try:
            canonical = TeamModel(name="Croatia", country="HR", is_placeholder=False)
            placeholder = TeamModel(name="Croacia", country=None, is_placeholder=True)
            session.add_all([canonical, placeholder])
            session.flush()
            session.add(TeamAliasModel(team=placeholder, alias="Croacia", normalized_alias="croacia"))
            session.add(TeamAliasModel(team=canonical, alias="Croatia", normalized_alias="croatia"))
            session.commit()

            with session.get_bind().begin() as conn:
                _migrate_to_v14(conn)

            session.expire_all()
            repo = EntityRepository(session)
            result = repo.find_team_by_alias("Croacia", "croatia")
            assert result is not None
            assert result.id == canonical.id
            assert result.is_placeholder is False
        finally:
            session.close()

    def test_placeholder_composition_intact(self, tmp_path):
        """After v14, the progol_slate_matches still has the same slate composition
        (same match UUIDs) — the merge only changes which team entity the match
        references, not the slate's match list."""

        from app.db.migrations import _migrate_to_v14
        from app.models.tables import (
            CompetitionModel,
            MatchModel,
            ProgolSlateMatchModel,
            ProgolSlateModel,
            TeamAliasModel,
            TeamModel,
        )

        session = _make_session(tmp_path, "comp.db")
        try:
            canonical = TeamModel(name="Croatia", country="HR", is_placeholder=False)
            placeholder = TeamModel(name="Croacia", country=None, is_placeholder=True)
            comp = CompetitionModel(
                name="International Friendlies", country=None, season=None, is_placeholder=False
            )
            home = TeamModel(name="England", country="EN", is_placeholder=False)
            session.add_all([canonical, placeholder, comp, home])
            session.flush()
            session.add(TeamAliasModel(team=placeholder, alias="Croacia", normalized_alias="croacia"))
            session.add(TeamAliasModel(team=canonical, alias="Croatia", normalized_alias="croatia"))
            session.flush()

            match = MatchModel(
                competition_id=comp.id,
                home_team_id=home.id,
                away_team_id=placeholder.id,
                kickoff_at=datetime(2026, 6, 13, tzinfo=timezone.utc),
            )
            session.add(match)
            session.flush()

            slate = ProgolSlateModel(
                draw_code="PG-T1",
                label="Test",
                week_type="weekend",
                registration_closes_at=datetime(2026, 12, 31, tzinfo=timezone.utc),
            )
            session.add(slate)
            session.flush()

            slate_match = ProgolSlateMatchModel(
                slate_id=slate.id,
                match_id=match.id,
                position=13,
            )
            session.add(slate_match)
            session.commit()

            match_id_before = match.id
            slate_match_id = slate_match.id

            with session.get_bind().begin() as conn:
                _migrate_to_v14(conn)

            # The slate_match still points to the SAME match UUID
            session.expire_all()
            sm = session.get(ProgolSlateMatchModel, slate_match_id)
            assert sm.match_id == match_id_before
        finally:
            session.close()


# ---------------------------------------------------------------------------
# 4. New Phase 9 alias additions
# ---------------------------------------------------------------------------

class TestPhase9TeamAliases:
    def setup_method(self):
        self.svc = NormalizationService()

    def test_canada_explicit(self):
        assert self.svc.normalize_team_name("Canada") == "canada"

    def test_canada_accented(self):
        assert self.svc.normalize_team_name("Canadá") == "canada"

    def test_korea_republic_maps_to_south_korea(self):
        assert self.svc.normalize_team_name("Korea Republic") == "south-korea"

    def test_ecuador_explicit(self):
        assert self.svc.normalize_team_name("Ecuador") == "ecuador"

    def test_belgica_maps_to_belgium(self):
        assert self.svc.normalize_team_name("Bélgica") == "belgium"
        assert self.svc.normalize_team_name("Belgica") == "belgium"

    def test_turquia_maps_to_turkey(self):
        assert self.svc.normalize_team_name("Turquía") == "turkey"
        assert self.svc.normalize_team_name("Turquia") == "turkey"

    def test_paises_bajos_maps_to_netherlands(self):
        assert self.svc.normalize_team_name("Países Bajos") == "netherlands"
        assert self.svc.normalize_team_name("Holanda") == "netherlands"

    def test_egypt_egipto_maps_correctly(self):
        assert self.svc.normalize_team_name("Egipto") == "egypt"

    def test_costa_de_marfil_maps_to_ivory_coast(self):
        assert self.svc.normalize_team_name("Costa de Marfil") == "ivory-coast"
        assert self.svc.normalize_team_name("Côte d'Ivoire") == "ivory-coast"

    def test_usa_variants(self):
        svc = self.svc
        assert svc.normalize_team_name("USA") == "usa"
        assert svc.normalize_team_name("Estados Unidos") == "usa"
        assert svc.normalize_team_name("United States") == "usa"

    def test_bosnia_y_herzegovina_maps_correctly(self):
        assert self.svc.normalize_team_name("Bosnia y Herzegovina") == "bosnia-herzegovina"

    def test_africa_del_sur_maps_to_south_africa(self):
        assert self.svc.normalize_team_name("África del Sur") == "south-africa"


class TestPhase10KoreaAliases:
    """Phase 10 — entity normalisation fix for Progol MS PDF Korea abbreviations.

    Root cause: the MS PDF uses "Re P. Corea" which produced alias-key
    "re p corea" — absent from TEAM_ALIAS_SLUGS — so the entity resolver
    created a new placeholder instead of linking to canonical South Korea.
    """

    def setup_method(self):
        self.svc = NormalizationService()

    def test_re_p_corea_maps_to_south_korea(self):
        assert self.svc.normalize_team_name("Re P. Corea") == "south-korea"

    def test_rep_corea_with_dot_maps_to_south_korea(self):
        assert self.svc.normalize_team_name("Rep. Corea") == "south-korea"

    def test_rep_corea_without_dot_maps_to_south_korea(self):
        assert self.svc.normalize_team_name("Rep Corea") == "south-korea"

    def test_korea_rep_maps_to_south_korea(self):
        assert self.svc.normalize_team_name("Korea Rep") == "south-korea"

    def test_north_korea_not_confused(self):
        assert self.svc.normalize_team_name("North Korea") == "north-korea"

    def test_korea_dpr_not_confused(self):
        assert self.svc.normalize_team_name("Korea DPR") == "korea-dpr"

    def test_corea_del_norte_not_confused(self):
        assert self.svc.normalize_team_name("Corea del Norte") == "north-korea"

    def test_existing_south_korea_aliases_unchanged(self):
        svc = self.svc
        assert svc.normalize_team_name("South Korea") == "south-korea"
        assert svc.normalize_team_name("Corea del Sur") == "south-korea"
        assert svc.normalize_team_name("Korea Republic") == "south-korea"
        assert svc.normalize_team_name("República de Corea") == "south-korea"
        assert svc.normalize_team_name("Corea") == "south-korea"


class TestMigrationV16:
    """v16 merges 'Re P. Corea' placeholder into canonical South Korea."""

    def _make_session(self, tmp_path, db_name: str):
        from app.db import session as db_session
        from app.db.migrations import run_migrations
        from app.db.session import configure_session

        configure_session(f"sqlite:///{tmp_path / db_name}")
        run_migrations(db_session.engine)
        return db_session.SessionLocal()

    def test_migration_is_idempotent_on_empty_db(self, tmp_path):
        from app.db.migrations import _migrate_to_v16

        session = self._make_session(tmp_path, "v16_idempotent.db")
        with session.get_bind().begin() as conn:
            _migrate_to_v16(conn)
            _migrate_to_v16(conn)
        session.close()

    def test_migration_merges_re_p_corea_into_south_korea(self, tmp_path):
        from sqlalchemy import select

        from app.db.migrations import _migrate_to_v16
        from app.models.tables import CompetitionModel, MatchModel, TeamModel, TeamAliasModel

        session = self._make_session(tmp_path, "v16_merge.db")
        try:
            canonical = TeamModel(name="South Korea", country="KR", is_placeholder=False)
            placeholder = TeamModel(name="Re P. Corea", country=None, is_placeholder=True)
            competition = CompetitionModel(
                name="International Friendlies", country=None, season=None, is_placeholder=False
            )
            away = TeamModel(name="Czech Republic", country="CZ", is_placeholder=False)
            session.add_all([canonical, placeholder, competition, away])
            session.flush()

            session.add(TeamAliasModel(team=placeholder, alias="Re P. Corea", normalized_alias="re-p-corea"))
            session.add(TeamAliasModel(team=canonical, alias="South Korea", normalized_alias="south-korea"))
            session.flush()

            match = MatchModel(
                competition_id=competition.id,
                home_team_id=placeholder.id,
                away_team_id=away.id,
                kickoff_at=__import__("datetime").datetime(2026, 6, 12, 8, 0, tzinfo=__import__("datetime").timezone.utc),
            )
            session.add(match)
            session.commit()

            match_id = match.id
            canonical_id = canonical.id

            with session.get_bind().begin() as conn:
                _migrate_to_v16(conn)

            session.expire_all()
            updated = session.get(MatchModel, match_id)
            assert updated is not None
            assert updated.home_team_id == canonical_id

            alias_row = session.scalars(
                select(TeamAliasModel).where(TeamAliasModel.normalized_alias == "re-p-corea")
            ).first()
            assert alias_row is not None
            assert alias_row.team_id == canonical_id
        finally:
            session.close()

    def test_migration_skips_conflict_when_canonical_match_exists(self, tmp_path):
        from app.db.migrations import _migrate_to_v16
        from app.models.tables import CompetitionModel, MatchModel, TeamModel, TeamAliasModel
        import datetime as dt

        session = self._make_session(tmp_path, "v16_conflict.db")
        try:
            canonical = TeamModel(name="South Korea", country="KR", is_placeholder=False)
            placeholder = TeamModel(name="Re P. Corea", country=None, is_placeholder=True)
            competition = CompetitionModel(
                name="International Friendlies", country=None, season=None, is_placeholder=False
            )
            away = TeamModel(name="Czech Republic", country="CZ", is_placeholder=False)
            session.add_all([canonical, placeholder, competition, away])
            session.flush()
            session.add(TeamAliasModel(team=placeholder, alias="Re P. Corea", normalized_alias="re-p-corea"))
            session.add(TeamAliasModel(team=canonical, alias="South Korea", normalized_alias="south-korea"))
            session.flush()

            kickoff = dt.datetime(2026, 6, 12, 16, 0, tzinfo=dt.timezone.utc)
            canonical_match = MatchModel(
                competition_id=competition.id,
                home_team_id=canonical.id,
                away_team_id=away.id,
                kickoff_at=kickoff,
            )
            placeholder_match = MatchModel(
                competition_id=competition.id,
                home_team_id=placeholder.id,
                away_team_id=away.id,
                kickoff_at=kickoff,  # same kickoff → conflict
            )
            session.add_all([canonical_match, placeholder_match])
            session.commit()

            with session.get_bind().begin() as conn:
                _migrate_to_v16(conn)

            session.expire_all()
            pm = session.get(MatchModel, placeholder_match.id)
            assert pm is not None
        finally:
            session.close()

    def test_migration_does_not_touch_composition_hash(self, tmp_path):
        from app.db.migrations import _migrate_to_v16
        from app.models.tables import ProgolSlateModel
        import datetime as dt

        session = self._make_session(tmp_path, "v16_hash.db")
        try:
            slate = ProgolSlateModel(
                draw_code="PGM-V16-1",
                label="Test",
                week_type="midweek",
                registration_closes_at=dt.datetime(2026, 12, 31, tzinfo=dt.timezone.utc),
                composition_hash="deadbeef5678",
                slate_version=1,
            )
            session.add(slate)
            session.commit()
            slate_id = slate.id

            with session.get_bind().begin() as conn:
                _migrate_to_v16(conn)

            session.expire_all()
            updated = session.get(ProgolSlateModel, slate_id)
            assert updated.composition_hash == "deadbeef5678"
        finally:
            session.close()


class TestPhase9CompetitionAliases:
    def setup_method(self):
        self.svc = NormalizationService()

    def test_fifa_international_friendlies(self):
        assert self.svc.normalize_competition_name("FIFA International Friendlies") == "international-friendlies"

    def test_nations_league_maps_to_international_friendlies(self):
        assert self.svc.normalize_competition_name("UEFA Nations League") == "international-friendlies"
        assert self.svc.normalize_competition_name("Nations League") == "international-friendlies"

    def test_nations_league_groups_map_correctly(self):
        svc = self.svc
        assert svc.normalize_competition_name("UEFA Nations League A") == "international-friendlies"
        assert svc.normalize_competition_name("UEFA Nations League B") == "international-friendlies"
        assert svc.normalize_competition_name("UEFA Nations League C") == "international-friendlies"

    def test_liga_de_naciones_maps_correctly(self):
        assert self.svc.normalize_competition_name("Liga de Naciones UEFA") == "international-friendlies"


# ---------------------------------------------------------------------------
# 5. DB migration v15 — placeholder competition relink
# ---------------------------------------------------------------------------

class TestMigrationV15:
    def test_migration_is_idempotent_on_empty_db(self, tmp_path):
        from app.db.migrations import _migrate_to_v15

        session = _make_session(tmp_path, "v15_idempotent.db")
        with session.get_bind().begin() as conn:
            _migrate_to_v15(conn)
            _migrate_to_v15(conn)
        session.close()

    def test_migration_relinks_progol_concurso_match_to_international_friendlies(self, tmp_path):

        from app.db.migrations import _migrate_to_v15
        from app.models.tables import CompetitionModel, MatchModel, TeamModel

        session = _make_session(tmp_path, "v15_relink.db")
        try:
            canonical_comp = CompetitionModel(
                name="International Friendlies", country=None, season=None, is_placeholder=False
            )
            placeholder_comp = CompetitionModel(
                name="Progol Concurso 9999", country=None, season=None, is_placeholder=True
            )
            home = TeamModel(name="South Korea", country="KR", is_placeholder=False)
            away = TeamModel(name="Czech Republic", country="CZ", is_placeholder=False)
            session.add_all([canonical_comp, placeholder_comp, home, away])
            session.flush()

            match = MatchModel(
                competition_id=placeholder_comp.id,
                home_team_id=home.id,
                away_team_id=away.id,
                kickoff_at=datetime(2026, 6, 12, 16, 0, tzinfo=timezone.utc),
            )
            session.add(match)
            session.commit()

            match_id = match.id
            canonical_comp_id = canonical_comp.id

            with session.get_bind().begin() as conn:
                _migrate_to_v15(conn)

            session.expire_all()
            updated = session.get(MatchModel, match_id)
            assert updated.competition_id == canonical_comp_id
        finally:
            session.close()

    def test_migration_skips_if_canonical_already_exists_at_same_slot(self, tmp_path):
        """When a canonical IF match already exists at the same (comp, home, away, kickoff),
        the placeholder match is NOT re-pointed — no unique-constraint violation."""
        from app.db.migrations import _migrate_to_v15
        from app.models.tables import CompetitionModel, MatchModel, TeamModel

        session = _make_session(tmp_path, "v15_skip.db")
        try:
            canonical_comp = CompetitionModel(
                name="International Friendlies", country=None, season=None, is_placeholder=False
            )
            placeholder_comp = CompetitionModel(
                name="Progol Concurso 9998", country=None, season=None, is_placeholder=True
            )
            home = TeamModel(name="Sweden", country="SE", is_placeholder=False)
            away = TeamModel(name="Tunisia", country="TN", is_placeholder=False)
            session.add_all([canonical_comp, placeholder_comp, home, away])
            session.flush()

            kickoff = datetime(2026, 6, 9, 18, 0, tzinfo=timezone.utc)
            canonical_match = MatchModel(
                competition_id=canonical_comp.id,
                home_team_id=home.id,
                away_team_id=away.id,
                kickoff_at=kickoff,
            )
            placeholder_match = MatchModel(
                competition_id=placeholder_comp.id,
                home_team_id=home.id,
                away_team_id=away.id,
                kickoff_at=kickoff + __import__("datetime").timedelta(seconds=1),
            )
            session.add_all([canonical_match, placeholder_match])
            session.commit()

            # Should not raise — the NOT EXISTS guard prevents the conflict
            with session.get_bind().begin() as conn:
                _migrate_to_v15(conn)

            session.expire_all()
            pm = session.get(MatchModel, placeholder_match.id)
            assert pm is not None
        finally:
            session.close()

    def test_migration_no_op_when_no_international_friendlies_comp(self, tmp_path):
        """If no International Friendlies competition exists, migration is a no-op."""
        from app.db.migrations import _migrate_to_v15
        from app.models.tables import CompetitionModel, MatchModel, TeamModel

        session = _make_session(tmp_path, "v15_noop.db")
        try:
            placeholder_comp = CompetitionModel(
                name="Progol Concurso 9997", country=None, season=None, is_placeholder=True
            )
            home = TeamModel(name="England", country="EN", is_placeholder=False)
            away = TeamModel(name="Croatia", country="HR", is_placeholder=False)
            session.add_all([placeholder_comp, home, away])
            session.flush()

            match = MatchModel(
                competition_id=placeholder_comp.id,
                home_team_id=home.id,
                away_team_id=away.id,
                kickoff_at=datetime(2026, 6, 12, 16, 0, tzinfo=timezone.utc),
            )
            session.add(match)
            session.commit()
            match_id = match.id
            original_comp_id = placeholder_comp.id

            with session.get_bind().begin() as conn:
                _migrate_to_v15(conn)

            session.expire_all()
            unchanged = session.get(MatchModel, match_id)
            assert unchanged.competition_id == original_comp_id
        finally:
            session.close()

    def test_composition_hash_unchanged_after_v15(self, tmp_path):
        from app.db.migrations import _migrate_to_v14, _migrate_to_v15
        from app.models.tables import ProgolSlateModel

        session = _make_session(tmp_path, "v15_hash.db")
        try:
            slate = ProgolSlateModel(
                draw_code="PG-V15-1",
                label="Test",
                week_type="weekend",
                registration_closes_at=datetime(2026, 12, 31, tzinfo=timezone.utc),
                composition_hash="deadbeef1234",
                slate_version=1,
            )
            session.add(slate)
            session.commit()
            slate_id = slate.id

            with session.get_bind().begin() as conn:
                _migrate_to_v14(conn)
                _migrate_to_v15(conn)

            session.expire_all()
            updated = session.get(ProgolSlateModel, slate_id)
            assert updated.composition_hash == "deadbeef1234"
        finally:
            session.close()


# ---------------------------------------------------------------------------
# 6. competition_operating_policy — Nations League and Friendly variants
# ---------------------------------------------------------------------------

class TestCompetitionPolicyForFriendlyVariants:
    def setup_method(self):
        from app.services.model_training_service import ModelTrainingService

        self._svc_class = ModelTrainingService

    def _policy(self, name: str) -> dict:
        from app.services.model_training_service import ModelTrainingService

        svc = ModelTrainingService.__new__(ModelTrainingService)
        return svc.competition_operating_policy(name)

    def test_international_friendlies_is_context_only(self):
        # Opción B del 2º pase: los amistosos nunca son "ready" — quedan
        # en context_only y no se permiten como live pick fuerte.
        p = self._policy("International Friendlies")
        assert p["competition_readiness"] == "context_only"
        assert p["live_pick_allowed"] is False

    def test_international_friendly_singular_is_context_only(self):
        p = self._policy("International Friendly")
        assert p["competition_readiness"] == "context_only"
        assert p["live_pick_allowed"] is False

    def test_nations_league_is_context_only(self):
        p = self._policy("UEFA Nations League")
        assert p["competition_readiness"] == "context_only"
        assert p["live_pick_allowed"] is False

    def test_progol_concurso_is_context_only(self):
        p = self._policy("Progol Concurso 2336")
        assert p["competition_readiness"] == "context_only"
        assert p["live_pick_allowed"] is False
